data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"
  features_path: "data/features/"
  
model:
  target: "will_purchase"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  
features:
  categorical:
    - "device_type"
    - "location"
    - "preferred_category"
  numerical:
    - "session_duration"
    - "age"
    - "avg_order_value"
    - "total_orders"
  temporal:
    - "session_start_hour"
    
mlflow:
  tracking_uri: "mlruns"
  experiment_name: "conversion_prediction"